<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="KirisameY.EventBus" Version="0.1.0" />
      <PackageReference Include="KirisameY.NotifiableCollections" Version="0.0.6" />
      <PackageReference Include="KirisameY.Numeric" Version="0.1.4" />
    </ItemGroup>

</Project>
